# SPDX-FileCopyrightText: 2017 Scott Shawcroft, written for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: Release Actions

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
    - name: Translate Repo Name For Build Tools filename_prefix
      id: repo-name
      run: |
        echo "repo-name=$(
        echo ${{ github.repository }} |
        awk -F '\/' '{ print tolower($2) }' |
        tr '_' '-'
        )" >> $GITHUB_OUTPUT
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Versions
      run: |
        python3 --version
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
    - name: Install deps
      run: |
        sudo apt-get install gettext
        pip install -r requirements.txt
    - name: Build assets
      run: circuitpython-build-bundles --filename_prefix ${{ steps.repo-name.outputs.repo-name }} --library_location libraries --library_depth 2 --package_folder_prefix "adafruit_, asyncio"
    - name: Upload Release Assets
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        asset_path: "bundles/*"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        upload_url: ${{ github.event.release.upload_url }}
    - name: Upload Assets To AWS S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: "[ -z \"$AWS_ACCESS_KEY_ID\" ] || aws s3 cp bundles/ s3://adafruit-circuit-python/bundles/adafruit --recursive --no-progress --region us-east-1"
